-- The Prisma schema and migrations will handle database creation and tables.
-- Optional: Postgres-friendly example indexes (use with caution; Prisma often creates necessary indexes automatically).
-- Uncomment and run against your Postgres database if needed.
-- CREATE INDEX IF NOT EXISTS idx_venues_city ON "Venue"("city");
-- CREATE INDEX IF NOT EXISTS idx_venues_approved ON "Venue"("isApproved");
-- CREATE INDEX IF NOT EXISTS idx_courts_sport ON "Court"("sport");
-- CREATE INDEX IF NOT EXISTS idx_bookings_date ON "Booking"("date");
-- CREATE INDEX IF NOT EXISTS idx_bookings_status ON "Booking"("status");
-- CREATE INDEX IF NOT EXISTS idx_bookings_user ON "Booking"("userId");
-- CREATE INDEX IF NOT EXISTS idx_bookings_court ON "Booking"("courtId");

-- Sample data insertion can be managed via Prisma seed instead.
